[project]
name = "ai-library-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yuhas", email = "yuhimsanda@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
ai-library-agent = "ai_library_agent:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
